apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: master
    spec:
      containers:
        - args:
            - -f
            - /mnt/locust/locustfile.py
            - --master
            - --expect-workers
            - "1"
          image: locustio/locust
          name: master
          ports:
            - containerPort: 8089
          resources: {}
          volumeMounts:
            - mountPath: /mnt/locust
              name: master-claim0
      restartPolicy: Always
      volumes:
        - name: master-claim0
          persistentVolumeClaim:
            claimName: master-claim0
status: {}
