apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: worker1
  name: worker1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: worker1
    spec:
      containers:
        - args:
            - -f
            - /mnt/locust/locustfile.py
            - --worker
            - --master-host
            - master
          image: locustio/locust
          name: worker1
          resources: {}
          volumeMounts:
            - mountPath: /mnt/locust
              name: worker1-claim0
      restartPolicy: Always
      volumes:
        - name: worker1-claim0
          persistentVolumeClaim:
            claimName: worker1-claim0
status: {}
